<?php
use OpenBKAdmin\Device;
use OpenBKAdmin\Helper\FirmwareFolderHelper;
use OpenBKAdmin\Helper\GuzzleFactory;
use OpenBKAdmin\Helper\OtaHelper;
use OpenBKAdmin\Helper\OpenBekenOtaScraper;
use OpenBKAdmin\OpenBeken;
use OpenBKAdmin\Update\FirmwareDownloader;

$OpenBeken=$container->get(OpenBeken::class);$devices=$OpenBeken->getDevices();$rawSelectedIds=$_POST['device_ids']??$_POST['device']??$_POST['devices']??[];if(empty($rawSelectedIds)&&isset($_POST['device_id']))$rawSelectedIds=(array)$_POST['device_id'];$selectedIds=array_values(array_unique(array_map('intval',(array)$rawSelectedIds)));$selected=array_values(array_filter($devices,static fn(Device $d)=>in_array((int)$d->id,$selectedIds,true)));$updateMode=(($_POST['update_mode']??'mass')==='individual')?'individual':'mass';
$targets=json_decode((string)($_POST['update_targets']??'{}'),true)?:[];$isAutomatic=false;foreach($targets as $target){if(($target['source']??'')==='automatic'){$isAutomatic=true;break;}}$deviceMeta=[];$otaErrors=[];$backupResults=[];
$detectPlatform=static function($status):string{$hardware=strtoupper((string)($status->StatusFWR->Hardware??''));$version=strtoupper((string)($status->StatusFWR->Version??''));if(preg_match('/(?:OPEN)?(BK\d+[A-Z]*|XR\d+|BL\d+|W\d+|LN\d+[A-Z]*|TR\d+|RTL\d+[A-Z0-9]*|ESP32[A-Z0-9_-]*)/',$hardware.' '.$version,$m))return preg_replace('/^OPEN/','',$m[1]);return'UNKNOWN';};
if($isAutomatic&&!empty($selected)){$requiredPlatforms=[];$statusByAddress=[];$namesByAddress=[];foreach($selected as $device){$address=$device->getAddress();if(!isset($statusByAddress[$address]))$statusByAddress[$address]=$OpenBeken->getOpenBekenStatus($device);if(!isset($namesByAddress[$address]))$namesByAddress[$address]=$OpenBeken->getOpenBekenNativeNames($device);$status=$statusByAddress[$address];$nativeNames=$namesByAddress[$address];$platform=$detectPlatform($status);$fullName=trim((string)($nativeNames->FullName??''));if($fullName==='')$fullName=trim((string)($status->OpenBeken->FriendlyName??''));if($fullName==='')$fullName=trim((string)($status->Status->DeviceName??''));if($fullName==='')$fullName=trim((string)($nativeNames->ShortName??''));if($fullName==='')$fullName=trim((string)($status->Status->FriendlyName[0]??$device->getName()));$currentFirmware=trim((string)($status->StatusFWR->Version??''));$currentVersion=$currentFirmware;if(preg_match('/(?:OPEN)?(?:BK\d+[A-Z]*|XR\d+|BL\d+|W\d+|LN\d+[A-Z]*|TR\d+|RTL\d+[A-Z0-9]*|ESP32[A-Z0-9_-]*)[_-](.+)$/i',$currentFirmware,$vm))$currentVersion=$vm[1];$deviceMeta[(int)$device->id]=['platform'=>$platform,'name'=>$fullName,'firmware'=>$currentFirmware,'version'=>$currentVersion];if($platform==='UNKNOWN')$otaErrors[]='Could not detect chipset for '.$fullName.' ('.$device->ip.').';else$requiredPlatforms[$platform]=true;}
if(empty($otaErrors)){try{$firmwarefolder=_DATADIR_.'firmwares/';FirmwareFolderHelper::clean($firmwarefolder);$client=GuzzleFactory::getClient($Config);$scraper=new OpenBekenOtaScraper($Config->read('auto_update_channel'),$client);$officialFirmwares=$scraper->getOtaFirmwares();$downloader=new FirmwareDownloader($client,$firmwarefolder);$otaHelper=new OtaHelper($Config,_BASEURL_);$targets=[];foreach(array_keys($requiredPlatforms)as$platform){if(!isset($officialFirmwares[$platform]))throw new RuntimeException('No official OTA Update asset was found for chipset '.$platform.'.');$firmware=$officialFirmwares[$platform];$path=$downloader->download($firmware['url']);$targets[$platform]=['minimalOtaUrl'=>'','otaUrl'=>$otaHelper->getFirmwareUrl($path),'targetVersion'=>$firmware['version'],'source'=>'automatic','platform'=>$platform];}}catch(Throwable $e){$otaErrors[]=$e->getMessage();}}
}
$deviceDisplayName=static function(Device $device)use($deviceMeta):string{if(!empty($deviceMeta[(int)$device->id]['name']))return$deviceMeta[(int)$device->id]['name'];$friendlyNames=array_values(array_filter($device->getFriendlyNames(),static fn($name)=>''!==trim((string)$name)));return!empty($friendlyNames)?(string)$friendlyNames[0]:$device->getName();};
// Safety backup before OTA. OpenBeken /dl is the existing full configuration
// dump used by OpenBKAdmin restore (WebGetConfig). Keep a timestamped copy per
// device ID. LittleFS/autoexec is separate storage and is not claimed as part
// of this dump; we never auto-restore after flashing.
if(!empty($selected)&&empty($otaErrors)){$backupDir=_DATADIR_.'ota-backups/';if(!is_dir($backupDir))@mkdir($backupDir,0775,true);$seen=[];foreach($selected as $device){$address=$device->getAddress();if(isset($seen[$address]))continue;$seen[$address]=true;try{$tmp=$OpenBeken->backup($device,$backupDir);$stamp=date('Ymd-His');$safe=preg_replace('/[^A-Za-z0-9._-]+/','_',basename($tmp,'.dmp'));$final=$backupDir.$stamp.'-'.$safe.'.dmp';if($tmp!==$final)@rename($tmp,$final);$backupResults[]=['id'=>$device->id,'name'=>$deviceDisplayName($device),'ok'=>true,'file'=>basename($final)];}catch(Throwable $e){$backupResults[]=['id'=>$device->id,'name'=>$deviceDisplayName($device),'ok'=>false,'error'=>$e->getMessage()];}}
}
?>
<div class="container mt-4 update-page"><h2 class="text-center mb-4"><?php echo$title;?></h2><?php if(empty($selected)){?><div class="alert alert-warning">No devices were selected for the firmware update.</div><?php }else{?><div class="card mb-4"><div class="card-body"><h5 class="card-title">Selected devices<?php echo$isAutomatic?' / detected chipsets':'';?></h5><p class="mb-2"><strong>Execution mode:</strong> <?php echo$updateMode==='mass'?'Mass (parallel)':'Individual (one at a time)';?> — maximum 5 status attempts per device.</p><ul class="mb-0"><?php foreach($selected as$d){$meta=$deviceMeta[(int)$d->id]??[];?><li><?php echo htmlspecialchars($deviceDisplayName($d),ENT_QUOTES,'UTF-8');?><?php if($isAutomatic){?> — <?php echo htmlspecialchars(trim((string)($meta['platform']??'UNKNOWN').' '.(string)($meta['version']??'')),ENT_QUOTES,'UTF-8');?><?php }?> — IP <?php echo htmlspecialchars($d->ip,ENT_QUOTES,'UTF-8');?></li><?php }?></ul></div></div>
<?php if(!empty($backupResults)){?><div class="alert alert-info"><strong>Pre-OTA configuration backup</strong><br><?php foreach($backupResults as$b){echo htmlspecialchars('Device '.$b['id'].' ('.$b['name'].'): '.($b['ok']?'saved as '.$b['file']:'backup failed - '.$b['error']),ENT_QUOTES,'UTF-8').'<br>'; }?><small>These are OpenBeken configuration dumps. LittleFS files such as autoexec.bat are separate and are not automatically restored.</small></div><?php }?>
<?php if(!empty($otaErrors)){?><div class="alert alert-danger"><strong>Firmware update stopped for safety.</strong><br><?php echo htmlspecialchars(implode(' ',$otaErrors),ENT_QUOTES,'UTF-8');?></div><?php }else{?><input type="hidden" id="update_targets" value="<?php echo htmlspecialchars(json_encode($targets),ENT_QUOTES,'UTF-8');?>"><div id="logGlobal" class="mb-3"></div><div id="progressbox"></div><script>const updateMode=<?php echo json_encode($updateMode);?>;const devices=<?php echo json_encode(array_map(static function(Device $d)use($deviceDisplayName,$deviceMeta){$m=$deviceMeta[(int)$d->id]??[];return['id'=>$d->id,'name'=>$deviceDisplayName($d),'chipset'=>$m['platform']??'','firmware'=>$m['firmware']??'','version'=>$m['version']??'','ip'=>$d->ip];},$selected));?>;</script><script src="<?php echo$urlHelper->js('compiled/device_update');?>"></script><?php }?><?php }?></div>
